### ISSUE TITLE
when i give me credits i get a error

### ISSUE THREAD

**Issue by IJE530** [ForzaMods/Forza-Mods-AIO#95] opened 2024-07-11 21:30 UTC
### Which version of the app?

2.3.0.0

### Description

---------------------------
Forza Mods AIO - Error
---------------------------
Address for this feature wasn't found!
Please try to activate the cheat again or try to restart the game and the tool.

If this error still occurs, please (Press Ctrl+C) to copy, and make an issue on the github repository or post the copied text on the aio mega-thread in our discord server (discord.gg/forzamods).

Feature: Bypass
Signature: 49 8B ? FF 50 ? 48 8D ? ? ? ? ? FF 15 ? ? ? ? 8B 8D

Tool Version: 2.3.0.0
Game: Forza Horizon 5
Game Version: 1.649.948.0
Platform: Steam
---------------------------
OK
---------------------------

### Screenshots

![Unbenannt111111](https://github.com/user-attachments/assets/122d6f28-0fdc-4313-944f-b71bfbcf24ff)

### Windows version

Windows 10 22H2 (19045)

**Comment by szaaamerik** [comment] 2024-07-11 21:37
duplicate of #74

**Closed by szaaamerik** 2024-07-11 21:37 UTC
Labels: bug, needs-triage
