### ISSUE TITLE
Error When Attempting to Use Any "Self/Vehicle" Mods

### ISSUE THREAD

**Issue by danbikes** [ForzaMods/Forza-Mods-AIO#90] opened 2024-07-04 09:24 UTC
### Which version of the app?

2.3.0.0

### Description

None of the "Self/Vehicle" mods seem to be working. I've tried all of them, but they all give this same error whenever you hit the "On/Off" toggle on the right side.

The error also appears when you try to toggle the mod back off after the error pops up the first time when you try to turn it on. Additionally, this error pops up when I try to toggle the "Free clothes" mod on and off. I've tried restarting the game and the tool as suggested, but nothing changed.

### Screenshots

![image](https://github.com/ForzaMods/Forza-Mods-AIO/assets/96049603/7cdd7632-f1a9-4731-8c3c-edcd1e0f6eff)

### Windows version

Windows 10 22H2 (19045)

**Comment by szaaamerik** [comment] 2024-07-04 09:39
duplicate of #74

**Closed as completed by szaaamerik** 2024-07-04 09:39 UTC
Labels: bug, duplicate
