### ISSUE TITLE
Addresss for this feature wasn´t found (FH5 Steam version) (Game Version : 1.649.948)

### ISSUE THREAD

**Issue by TheCiROMG** [ForzaMods/Forza-Mods-AIO#93] opened 2024-07-11 09:45 UTC
### Which version of the app?

2.3.0.0

### Description

![Forza-Mods-AIO_g1eXKfSDIt](https://github.com/ForzaMods/Forza-Mods-AIO/assets/61605643/93479987-aab8-4681-9c30-97ff6b6df27e)

### Screenshots

![Forza-Mods-AIO_ZRpwAR4a42](https://github.com/ForzaMods/Forza-Mods-AIO/assets/61605643/7cb44803-e7c8-4c97-9e66-45deae9b5deb)

### Windows version

Windows 11 23H2 (22631)

**Comment by jiqimao888** [comment] 2024-07-11 10:03
The address of FH5 has been updated, while the address of this cheat machine is the old address. We just need to wait for the author to release it

**Comment by szaaamerik** [comment] 2024-07-11 21:37
duplicate of #74

**Closed as completed by szaaamerik** 2024-07-11 21:37 UTC
Labels: bug, duplicate
