### ISSUE TITLE
Bug title

### ISSUE THREAD

**Issue by ddfrg5e2** [ForzaMods/Forza-Mods-AIO#91] opened 2024-07-08 21:33 UTC
### Which version of the app?

2.2.0.0

### Description

---------------------------
Forza Mods AIO - Error
---------------------------
Address for this feature wasn't found!
Please try to activate the cheat again or try to restart the game and the tool.

If this error still occurs, please (Press Ctrl+C) to copy, and make an issue on the github repository or post the copied text on the aio mega-thread in our discord server (discord.gg/forzamods).

Feature: Bypass
Signature: 49 8B ? FF 50 ? 48 8D ? ? ? ? ? FF 15 ? ? ? ? 8B 8D

Tool Version: 2.2.0.0
Game: Forza Horizon 5
Game Version: 3.649.948.0
Platform: MS
---------------------------
OK   
--------------------------- 

### Screenshots

![Screenshot 2024-07-09 003009](https://github.com/ForzaMods/Forza-Mods-AIO/assets/175062721/9840df07-235b-4546-8852-40d34ad1f4cf)

### Windows version

Windows 11 24H2 (26052)

**Comment by szaaamerik** [comment] 2024-07-11 21:38
duplicate of #74

**Closed as completed by szaaamerik** 2024-07-11 21:38 UTC
Labels: bug, duplicate
