### ISSUE TITLE
Bug title

### ISSUE THREAD

**Issue by TaLESue** [ForzaMods/Forza-Mods-AIO#88] opened 2024-07-01 13:00 UTC
### Which version of the app?

2.3.0.0

### Description

vFH4 and FH5, manipulation and tuning are not available

### Screenshots

<img width="601" alt="微信图片_20240701205937" src="https://github.com/ForzaMods/Forza-Mods-AIO/assets/174342563/74938646-eb60-4935-88ea-c41ffb87d0b7">

### Windows version

Windows 11 23H2 (22631)

**Comment by JimmyFlo** [comment] 2024-07-03 20:39
same thing here

**Comment by hooke007** [comment] 2024-07-05 14:14
https://github.com/ForzaMods/Forza-Mods-AIO/issues/74

**Comment by EP1PHANEIA** [comment] 2024-07-07 14:46
bro在度假

**Comment by szaaamerik** [comment] 2024-07-11 21:38
duplicate of #74

**Closed as completed by szaaamerik** 2024-07-11 21:38 UTC
Labels: bug, duplicate
