### ISSUE TITLE
Everytime I click "Scan" it doesnt work

### ISSUE THREAD

**Issue by etiennebs** [ForzaMods/Forza-Mods-AIO#114] opened 2024-09-22 16:34 UTC
### Which version of the app?

2.4.0.1

### Description

**Address for this feature wasn't found!**
Please try to activate the cheat again or try to restart the game and the tool.

If this error still occurs, please (Press Ctrl+C) to copy, and make an issue on the github repository or post the copied text on the aio mega-thread in our discord server (discord.gg/forzamods).

Feature: Local Player Hook
Signature: F3 0F ? ? ? 49 8B ? 49 8B ? 0F 28

Tool Version: 2.4.0.1
Game: Forza Horizon 4
Game Version: 1.478.564.2
Platform: MS

### Screenshots

I just want a fast car :sob

### Windows version

Windows 10 22H2 (19045)

### Additional context

none

**Comment by szaaamerik** [comment] 2024-09-22 17:33
Dupe of #38

**Closed as completed by szaaamerik** 2024-09-22 17:33 UTC
Labels: bug, duplicate
