### ISSUE TITLE
Address wasn't found

### ISSUE THREAD

**Issue by M78-556** [ForzaMods/Forza-Mods-AIO#86] opened 2024-06-27 13:53 UTC
### Which version of the app?

Forza Horizon 5

### Description

---------------------------
Forza Mods AIO - Error
---------------------------
Address for this feature wasn't found!
Please try to activate the cheat again or try to restart the game and the tool.

If this error still occurs, please (Press Ctrl+C) to copy, and make an issue on the github repository or post the copied text on the aio mega-thread in our discord server (discord.gg/forzamods).

Feature: Bypass
Signature: 49 8B ? FF 50 ? 48 8D ? ? ? ? ? FF 15 ? ? ? ? 8B 8D

Tool Version: 2.3.0.0
Game: Forza Horizon 5
Game Version: 1.649.948.0
Platform: Steam
---------------------------
确定   
---------------------------

### Screenshots

![批注 2024-06-27 215224](https://github.com/ForzaMods/Forza-Mods-AIO/assets/174024615/93ea562b-5660-40c8-b15a-d7f1a30d3c7e)

### Windows version

Windows 10 22H2 (19045)

**Comment by Yicheng-1218** [comment] 2024-06-27 16:06
Dude , on the releases page, it says "This release was designed to work with FH5 v646.267."
For now, version 2.3.0.0 is outdated!

**Comment by szaaamerik** [comment] 2024-06-27 18:53
duplicate of #74

**Closed as completed by szaaamerik** 2024-06-27 18:53 UTC
Labels: bug, duplicate
