### ISSUE TITLE
Nothing is Working except free cars Forza Horizon 5

### ISSUE THREAD

**Issue by TheGhost00786** [ForzaMods/Forza-Mods-AIO#89] opened 2024-07-03 04:51 UTC
### Which version of the app?

1.649.948

### Description

Nothing works credits wheel spin speed hacks points nothing working

### Screenshots

look at this
![2024-07-03_094842](https://github.com/ForzaMods/Forza-Mods-AIO/assets/139939315/435844af-1e4e-482b-a763-562cd3df763d)

### Windows version

Insider Build (xxxxx)

### Additional context

Windows Version 24h2 26100.1000

**Comment by szaaamerik** [comment] 2024-07-03 09:11
duplicate of #74

**Closed as completed by szaaamerik** 2024-07-03 09:11 UTC
Labels: bug, duplicate
