### ISSUE TITLE
Can't get any credits or xp

### ISSUE THREAD

**Issue by Ther4py** [ForzaMods/Forza-Mods-AIO#82] opened 2024-06-23 16:58 UTC
### Which version of the app?

2.3.0.0

### Description

Getting error msg while trying to add credits

### Screenshots

![Screenshot_1](https://github.com/ForzaMods/Forza-Mods-AIO/assets/82467241/9099f99b-7057-4571-a064-58b1ac7ce91f)
https://prnt.sc/UKZAA9ojURxs

### Windows version

Windows 11 23H2 (22631)

**Comment by szaaamerik** [comment] 2024-06-23 17:52
duplicate of #74
going to close this

**Closed as completed** 2024-06-23 17:52 UTC
Labels: bug, duplicate
