### ISSUE TITLE
Wont let me add credits or free clothing

### ISSUE THREAD

**Issue by TheRealDrLow** [ForzaMods/Forza-Mods-AIO#94] opened 2024-07-11 20:14 UTC
### Which version of the app?

Recent 2024 

### Description

So I just downloaded the game and started on my fresh new account, i use the forza aio and it gave me the free cars and all the cars but the credits, clothing and ect freeze the game and boots me out, what could be the issue here?

### Screenshots

i dont have any screenshots.

### Windows version

Windows 10 22H2 (19045)

**Comment by szaaamerik** [comment] 2024-07-11 21:37
duplicate of #74

**Closed as completed by szaaamerik** 2024-07-11 21:37 UTC
Labels: bug, duplicate

**Comment by TheRealDrLow** [comment] 2024-07-11 22:31
So its not fixed yet due to your on a holiday still?

**Comment by szaaamerik** [comment] 2024-07-12 20:52
no I'm planning something bigger for the aio.

**Comment by TheRealDrLow** [comment] 2024-07-13 01:40
Awesome! Cant Wait to see this!!

**Comment by yxfyyds** [comment] 2024-07-15 13:26
> no I'm planning something bigger for the aio.

Hello author. I know you are planning something bigger for AIO. I also hope that you can add several features to the new version. Firstly, you can unlock various specific items in the appreciation section one by one, such as those that are only available for limited time events (Evolution World Appreciation), as well as those that are difficult to obtain, such as appreciation completed through online activities and appreciation for painting and photo training activities. In short, the changes in the appreciation score compared to the previous version are more advanced. Secondly, can the medal be obtained through AIO modification. Thirdly, the car horn can also be unlocked through AIO for scheduled actions. Fourthly, cannot the flight function be activated through the new version? Flyhack 

![36083589D9BB514EC5D87F7498F04816](https://github.com/user-attachments/assets/96148b9b-8ea0-4a09-a761-dd9ace7d4d01)
![ECAAEC712601AFE957F5ED81F4CDAF32](https://github.com/user-attachments/assets/24a5ad5d-9329-4c89-99ab-16b881aad1a9)
![Uploading BEC4FB94A33DE23971C4CFD9336D4A7D.png…]()
